import {randomBytes} from 'node:crypto';
export const uid=()=>randomBytes(16).toString('hex');
export const reject=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const integer=(n,min,max)=>Number.isSafeInteger(n)&&n>=min&&n<=max;
const names=['بوراتا مع الطماطم','شوربة القرع المشوي','دجاج مشوي مع الخضروات','ريزوتو الفطر','قاروص بزبدة الليمون','سلطة الحديقة','فون دان الشوكولاتة','كركديه مثلج'];
const descriptions=['Creamy burrata, ripe tomatoes and fresh basil.','Silky roasted pumpkin, gently seasoned.','Grilled chicken with seasonal vegetables.','Creamy rice with wild mushrooms.','Seabass with lemon butter and greens.','A colorful bowl of seasonal vegetables.','Warm chocolate cake with a soft center.','Chilled hibiscus, served over ice.'];
const descriptionsAr=['بوراتا كريمية وطماطم ناضجة وريحان طازج.','شوربة قرع مشوي ناعمة بتتبيلة خفيفة.','دجاج مشوي مع خضروات موسمية.','أرز كريمي مع تشكيلة من الفطر.','قاروص مع زبدة الليمون والخضروات.','تشكيلة ملونة من الخضروات الموسمية.','كيك شوكولاتة دافئ بقلب ناعم.','كركديه بارد يقدم مع الثلج.'];
export function migratePlatform(s){const before=JSON.stringify([s.platformVersion,s.branches,s.menu,s.tables]);
 s.branches||=[{id:'main',name:s.settings.branch,nameAr:'الزمالك، القاهرة',active:true,pickup:true,delivery:s.settings.deliveryEnabled,deliveryAreas:['Zamalek','الزمالك'],paymentProvider:'auto',reservations:true}];
 s.splits||=[];s.shares||=[];s.ratings||=[];s.integrations||={};s.revision||=0;
 for(const m of s.menu){const n=/^m[0-7]$/.test(m.id)?Number(m.id.slice(1)):-1;Object.assign(m,{nameAr:m.nameAr||(n>=0?names[n]:''),description:m.description||(n>=0?descriptions[n]:''),descriptionAr:m.descriptionAr||(n>=0?descriptionsAr[n]:''),imageIndex:m.imageIndex??n,spice:m.spice??0,prepMinutes:m.prepMinutes??null,ingredients:m.ingredients||[],modifiers:m.modifiers||[],branchIds:m.branchIds||['main']});}
 for(const branch of s.branches){branch.reservations??=branch.id==='main';}for(const t of s.tables){t.branchId||='main';t.features||=[];t.reservable??=true;}
 for(const v of s.visits)v.branchId||='main';s.platformVersion=2;return before!==JSON.stringify([s.platformVersion,s.branches,s.menu,s.tables]);
}
export function billFor(s,v){const subtotal=s.orders.filter(o=>o.visitId===v.id&&o.status!=='cancelled').reduce((n,o)=>n+o.total,0),total=subtotal+v.fee,paid=s.payments.filter(p=>p.visitId===v.id&&p.kind==='bill').reduce((n,p)=>n+p.amount,0);return {subtotal,fee:v.fee,total,credit:v.credit,paid,due:Math.max(0,total-v.credit-paid)};}
export function quoteLines(s,lines,branchId='main'){
 if(!Array.isArray(lines)||!lines.length||lines.length>50)reject('Your cart is empty.');const counts={};
 const result=lines.map(l=>{const m=s.menu.find(m=>m.id===l.id);if(!m||!m.available||!m.branchIds?.includes(branchId)||!integer(l.qty,1,50))reject('An item is unavailable.',409);counts[m.id]=(counts[m.id]||0)+l.qty;const selected=Array.isArray(l.options)?l.options:[];if(new Set(selected).size!==selected.length)reject('Duplicate options.');const modifiers=selected.map(id=>m.modifiers.find(x=>x.id===id));if(modifiers.some(x=>!x||!x.available))reject('An option is unavailable.',409);for(const mod of m.modifiers)if(mod.required&&!selected.includes(mod.id))reject('Choose the required options.');const price=m.price+modifiers.reduce((n,x)=>n+x.price,0);if(l.price!==undefined&&l.price!==price)reject('A menu price changed. Refresh your cart and confirm again.',409);return {id:m.id,name:m.name,nameAr:m.nameAr,qty:l.qty,price,station:m.station,options:modifiers.map(x=>({id:x.id,name:x.name,price:x.price}))};});
 for(const [id,qty]of Object.entries(counts))if(s.menu.find(m=>m.id===id).stock<qty)reject('Insufficient portions.',409);return result;
}
export function placeOnline(s,b){const branch=s.branches.find(x=>x.id===b.branchId&&x.active);if(!branch||!['pickup','delivery'].includes(b.type)||!branch[b.type])reject('Choose an available branch and fulfillment method.');if(typeof b.name!=='string'||!b.name.trim()||b.name.length>100||typeof b.contact!=='string'||!b.contact.trim()||b.contact.length>100)reject('Enter your name and contact.');if(b.type==='delivery'&&(typeof b.address!=='string'||!b.address.trim()||b.address.length>500||!branch.deliveryAreas.includes(b.area)))reject('Choose an eligible delivery area and enter your address.');
 if(branch.paymentProvider!=='auto'&&b.payment!==branch.paymentProvider)reject('Choose the branch payment method.');const lines=quoteLines(s,b.lines,branch.id),v={id:uid(),token:uid(),type:b.type,branchId:branch.id,name:b.name,contact:b.contact,address:b.address||'',status:'open',locked:false,credit:0,fee:b.type==='delivery'?s.settings.deliveryFee:0,created:Date.now()};s.visits.push(v);
 const order={id:uid(),number:s.orders.length+1,visitId:v.id,branchId:branch.id,type:v.type,name:v.name,lines,total:lines.reduce((n,l)=>n+l.qty*l.price,0),notes:String(b.notes||'').slice(0,500),status:'received',version:0,created:Date.now()};
 if(b.payment==='demo'){if(process.env.PAYMENT_MODE==='live')reject('Simulated payments are disabled.',403);v.locked=true;s.payments.push({id:uid(),visitId:v.id,kind:'bill',amount:order.total+v.fee,provider:'demo',at:Date.now()});}else if(!['stripe','paymob'].includes(b.payment))reject('Choose a payment method.');
 for(const l of lines){const m=s.menu.find(m=>m.id===l.id);m.stock-=l.qty;m.version++;}s.orders.push(order);return {token:v.token,orderId:order.id,amount:order.total+v.fee};
}
export function splitView(s,v,origin){const split=s.splits.find(x=>x.visitId===v.id&&x.status==='active');return split?{id:split.id,total:split.total,created:split.created,shares:s.shares.filter(x=>x.splitId===split.id).map(x=>({id:x.id,name:x.name,amount:x.amount,status:x.status,url:origin+'/s/'+x.token})),bill:billFor(s,v)}:null;}
export function createSplit(s,v,b,origin){if(v.status!=='open'||!integer(b.people,2,20))reject('Choose between 2 and 20 people.');if(s.splits.some(x=>x.visitId===v.id&&x.status==='active'))return splitView(s,v,origin);if((s.checkouts||[]).some(c=>c.visitId===v.id&&c.status==='pending'))reject('Finish the pending checkout first.',409);const due=billFor(s,v).due;if(due<b.people)reject('The remaining balance is too small to split.');const split={id:uid(),visitId:v.id,total:due,status:'active',created:Date.now()};s.splits.push(split);v.locked=true;for(let i=0;i<b.people;i++)s.shares.push({id:uid(),token:uid(),splitId:split.id,visitId:v.id,amount:Math.floor(due/b.people)+(i<due%b.people?1:0),name:String(b.names?.[i]||'').trim().slice(0,60),status:'pending',created:Date.now()});return splitView(s,v,origin);}
export function shareFor(s,token){const share=s.shares.find(x=>x.token===token);if(!share)reject('Payment invitation not found.',404);return share;}
export function shareView(s,x){const v=s.visits.find(v=>v.id===x.visitId);return {name:x.name,amount:x.amount,status:x.status,restaurant:s.settings.name,branch:s.branches.find(b=>b.id===v.branchId)?.name,remaining:billFor(s,v).due,canRate:x.status==='paid',checkout:(s.checkouts||[]).find(c=>c.shareId===x.id&&c.status==='pending')?.url||null};}
export function payShare(s,x,b){if(!b.name?.trim()||b.name.length>60)reject('Enter your first name.');if(x.status==='paid')return shareView(s,x);if(x.status!=='pending')reject('This payment invitation is no longer active.',409);if((s.checkouts||[]).some(c=>c.shareId===x.id&&c.status==='pending'))reject('Complete the pending checkout first.',409);if(process.env.PAYMENT_MODE==='live')reject('Simulated payments are disabled.',403);const v=s.visits.find(v=>v.id===x.visitId);if(v.status!=='open'||billFor(s,v).due<x.amount)reject('Balance changed.',409);x.name=b.name.trim();x.status='paid';x.paidAt=Date.now();s.payments.push({id:uid(),visitId:v.id,shareId:x.id,kind:'bill',amount:x.amount,provider:'demo',at:Date.now()});return shareView(s,x);}
export function addRating(s,v,b,shareId){if(!s.payments.some(p=>p.visitId===v.id&&p.kind==='bill'&&(!shareId||p.shareId===shareId)))reject('Complete payment before rating.',409);if(!integer(b.overall,1,5)||['food','service','speed','value'].some(k=>b[k]!=null&&!integer(b[k],1,5)))reject('Choose a rating from one to five.');const existing=s.ratings.find(r=>r.visitId===v.id&&r.shareId===(shareId||null));if(existing)return {ok:true};s.ratings.push({id:uid(),visitId:v.id,branchId:v.branchId||'main',tableId:v.tableId||null,orderIds:s.orders.filter(o=>o.visitId===v.id).map(o=>o.id),shareId:shareId||null,overall:b.overall,food:b.food??null,service:b.service??null,speed:b.speed??null,value:b.value??null,comment:String(b.comment||'').slice(0,1000),at:Date.now()});return {ok:true};}
export function insights(s){const orders=s.orders.filter(o=>o.status!=='cancelled'),today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(Date.now()),payments=s.payments.filter(p=>p.kind==='bill'),day=p=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(p.at)===today;return {revenueToday:payments.filter(day).reduce((n,p)=>n+p.amount,0),ordersToday:orders.filter(o=>day({at:o.created})).length,activeTables:s.visits.filter(v=>v.status==='open'&&v.tableId).length,lowStock:s.menu.filter(m=>m.available&&m.stock<6),ratings:{count:s.ratings.length,average:s.ratings.length?s.ratings.reduce((n,r)=>n+r.overall,0)/s.ratings.length:null,details:['food','service','speed','value'].map(k=>{const rows=s.ratings.filter(r=>r[k]);return {key:k,count:rows.length,average:rows.length?rows.reduce((n,r)=>n+r[k],0)/rows.length:null}})},stations:[...new Set(s.menu.map(m=>m.station))].map(name=>({name,portions:orders.filter(o=>['received','preparing'].includes(o.status)).flatMap(o=>o.lines).filter(l=>l.station===name).reduce((n,l)=>n+l.qty,0)})),recentPayments:payments.slice(-10).reverse(),customers:Object.values(s.visits.filter(v=>v.contact).reduce((a,v)=>{a[v.contact]||={name:v.name,contact:v.contact,visits:0,spent:0};a[v.contact].visits++;a[v.contact].spent+=payments.filter(p=>p.visitId===v.id).reduce((n,p)=>n+p.amount,0);return a},{}))};}
